### ISSUE TITLE
Allow configuring the root of the Rust project

### ISSUE THREAD

**Issue by jonasbb** [actions-rust-lang/audit#2]
The action currently assumes that the Rust project is directly in the root of the repository. This is not always the case, but Action cannot be configured with a working directory. Instead, a separate input is necessary. This was also requested as `PROJECT_PATH` for the audit-check action. https://github.com/actions-rs/audit-check/issues/116

**Comment by faern** [comment]
Thank you @mbergkvist for adding this feature. Would it be possible to cut a release? I would love to use the `file` field in a CI job where we have multiple Rust workspaces in a single git repository, and would like to audit all of them.

**Comment by mbergkvist** [comment]
@jonasbb If you plan to make a new release, have a look at #56 and see if that can be included in the release too.

**Comment by jonasbb** [comment]
I released a new version and included #56 in it.

**Comment by faern** [comment]
Thank you for a very swift response and release! :rocket: This works really well for us!
