### ISSUE TITLE
No tag for release 1.1.7

### ISSUE THREAD

**Issue by faern** [actions-rust-lang/audit#33]
In the changelog I can see you have released version 1.1.7. But there is no git tag for it. Also, when I try to use this action with `uses: actions-rust-lang/audit@v1` it still uses 1.1.6. If I specifically specify 1.1.7 I get this error:
```
Error: Unable to resolve action `actions-rust-lang/audit@v1.1.7`, unable to find version `v1.1.7`
```

**Comment by jonasbb** [comment]
Thank you. I must have forgotten. I created the tag and created a new release.

**Comment by faern** [comment]
Thank you for the quick response! Now it pulls in `1.1.7` when just specifying `@1` :sparkles:
