### ISSUE TITLE
TypeError: sequence item 23: expected str instance, NoneType found

### ISSUE THREAD

**Issue by autarch** [actions-rust-lang/audit#40]
I just started seeing this show up in one of my projects. You can see a failed run at https://github.com/houseabsolute/ubi/actions/runs/5945628024/job/16126518444

I'm not sure what's going on here. It just appeared out of the blue.

**Comment by jonasbb** [comment]
Hi, it appears that the webpki advisories did not have URLs assigned. I made the code more robust in the presence of missing values to mitigate such problems in the future.

**Comment by autarch** [comment]
Thanks!
