### ISSUE TITLE
Who controls `actions-rust-lang`?

### ISSUE THREAD

**Issue by bitdivine** [actions-rust-lang/audit#45]
I love the idea of an organisation providing a set of Rust actions.  @svartalf provided [a useful set of Rust actions](https://github.com/actions-rs) that were highly appreciated but he then effectively disappeared from the scene.  An organisation should hopefully be better at surviving a member being hit by the metaphorical bus.

But...

Who is `actions-rust-lang`?

Does the organization have some sort of governing body?

Is the governing body able to assign new maintainers if some fall away?

How does the organization deal with security issues in the actions themselves, such as a maintainer going evil and exfiltrating keys?

**Comment by jonasbb** [comment]
This is an organization like actions-rs. It doesn't exist outside of GitHub. It is a tool to group these related repositories together. So far most of the work here has been done by me, but I am not alone in having access to it. Your questions haven't come up so far, but these topics also weren't a problem.

**Comment by bitdivine** [comment]
Thank you for the clarification.  Group of collaborating developers is fine! :-)  The organization [has no public members](https://github.com/orgs/actions-rust-lang/people) which raised some eyebrows but we can check the committers to a given repository and of course check the commit history.
