### ISSUE TITLE
actions/cache@v4 does not exist

### ISSUE THREAD

**Issue by ISibboI** [actions-rust-lang/audit#53]
Maybe it was deleted over night? I suddenly get failing cargo audits saying that actions/cache@v4 cannot be found. Checking out the actions/cache repo, there is no v4 tag at the moment.

**Comment by mbergkvist** [comment]
https://github.com/actions-rust-lang/audit/commit/fe37c9c299a0b7c1f196d96d35c0125b17c7bd92
