### ISSUE TITLE
make working-directory configurable

### ISSUE THREAD

**Issue by DenuxPlays** [actions-rust-lang/audit#71]
Hey,

I want to use this workflow in my monorepo.
I can configure where the Cargo.lock file is located but not where the audit.toml file is located.
So I think the easiest solution is to make the working-directoy configurable.

**Comment by jonasbb** [comment]
Hey, thanks for the suggestion. It is indeed unfortunate that cargo audit isn't more flexible here, for example by specifying a path to an acceptable audit.toml. I published v1.2 with a `workingDirectory` input. I hope you can test it out and report back if that solves your issue.
