### ISSUE TITLE
cargo install fails with cargo v1.80

### ISSUE THREAD

**Issue by bekriebel** [actions-rust-lang/audit#88]
This fails when installing cargo audit with cargo v1.80 due to an issue with the locked version of the `time` dependency. Removing `--locked` from the install command allows the command to work.

`cargo install cargo-audit --vers 0.20.0 --no-default-features`

**Comment by jonasbb** [comment]
Installing with `--locked` was previously necessary since otherwise v0.20 would have runtime problems #72.
It seems that currently it works without `--locked`. I will push an update.
